apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "heytaco.fullname" . }}
  labels:
    {{- include "heytaco.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts:
        - {{ .Values.ingress.hostname | quote }}
      secretName: {{ include "heytaco.fullname" . }}-tls
  rules:
    - host: {{ .Values.ingress.hostname | quote }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "heytaco.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
